/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

/* Table schema:
CREATE TABLE kv_store_16010b6f (
  key TEXT NOT NULL PRIMARY KEY,
  value JSONB NOT NULL
);
*/

// View at https://supabase.com/dashboard/project/lmkthofnydxxgowryjcz/database/tables

// This file provides a simple key-value interface for storing Figma Make data. It should be adequate for most small-scale use cases.
import { createClient } from "jsr:@supabase/supabase-js@2.49.8";

// Reuse single client instance instead of creating new one each time
const supabaseClient = createClient(
  Deno.env.get("SUPABASE_URL")!,
  Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,
  {
    auth: {
      autoRefreshToken: false,
      persistSession: false,
    },
    db: {
      schema: 'public',
    },
    global: {
      headers: {
        'Connection': 'keep-alive',
      },
    },
  }
);

// Helper to add timeout to operations
async function withTimeout<T>(promise: Promise<T>, timeoutMs = 30000): Promise<T> {
  return Promise.race([
    promise,
    new Promise<T>((_, reject) =>
      setTimeout(() => reject(new Error(`Database query timed out after ${timeoutMs}ms`)), timeoutMs)
    )
  ]);
}

// Set stores a key-value pair in the database.
export const set = async (key: string, value: any): Promise<void> => {
  const { error } = await withTimeout(
    supabaseClient.from("kv_store_16010b6f").upsert({
      key,
      value
    }),
    15000 // Increased from 5000ms to handle cold starts
  );
  if (error) {
    throw new Error(error.message);
  }
};

// Get retrieves a key-value pair from the database.
export const get = async (key: string): Promise<any> => {
  const { data, error } = await withTimeout(
    supabaseClient.from("kv_store_16010b6f").select("value").eq("key", key).maybeSingle(),
    15000 // Increased from 5000ms to handle cold starts
  );
  if (error) {
    throw new Error(error.message);
  }
  return data?.value;
};

// Delete deletes a key-value pair from the database.
export const del = async (key: string): Promise<void> => {
  const { error } = await withTimeout(
    supabaseClient.from("kv_store_16010b6f").delete().eq("key", key),
    15000 // Increased from 5000ms to handle cold starts
  );
  if (error) {
    throw new Error(error.message);
  }
};

// Sets multiple key-value pairs in the database.
export const mset = async (keys: string[], values: any[]): Promise<void> => {
  const { error } = await withTimeout(
    supabaseClient.from("kv_store_16010b6f").upsert(keys.map((k, i) => ({ key: k, value: values[i] }))),
    20000 // Increased from 10000ms for batch operations
  );
  if (error) {
    throw new Error(error.message);
  }
};

// Gets multiple key-value pairs from the database.
export const mget = async (keys: string[]): Promise<any[]> => {
  const { data, error } = await withTimeout(
    supabaseClient.from("kv_store_16010b6f").select("value").in("key", keys),
    20000 // Increased from 10000ms for batch operations
  );
  if (error) {
    throw new Error(error.message);
  }
  return data?.map((d) => d.value) ?? [];
};

// Deletes multiple key-value pairs from the database.
export const mdel = async (keys: string[]): Promise<void> => {
  const { error } = await withTimeout(
    supabaseClient.from("kv_store_16010b6f").delete().in("key", keys),
    20000 // Increased from 10000ms for batch operations
  );
  if (error) {
    throw new Error(error.message);
  }
};

// PostgREST caps each response at 1000 rows by default. Without pagination, prefix scans
// silently drop newer keys (e.g. recent orders), which makes order history look empty.
const PREFIX_PAGE_SIZE = 1000;

// Search for key-value pairs by prefix.
export const getByPrefix = async (prefix: string): Promise<any[]> => {
  const allValues: any[] = [];
  let offset = 0;

  for (;;) {
    const { data, error } = await withTimeout(
      supabaseClient
        .from("kv_store_16010b6f")
        .select("key, value")
        .like("key", prefix + "%")
        .order("key", { ascending: true })
        .range(offset, offset + PREFIX_PAGE_SIZE - 1),
      30000
    );
    if (error) {
      throw new Error(error.message);
    }
    const rows = data ?? [];
    for (const row of rows) {
      allValues.push(row.value);
    }
    if (rows.length < PREFIX_PAGE_SIZE) {
      break;
    }
    offset += PREFIX_PAGE_SIZE;
  }

  return allValues;
};

/** True for real vendor profile docs under vendor:{id}. Excludes vendor:audience:* (arrays) and bad values. */
export function isVendorProfileKvEntry(key: string, value: unknown): boolean {
  if (!key.startsWith("vendor:")) return false;
  if (key.startsWith("vendor:audience:")) return false;
  if (value == null || Array.isArray(value) || typeof value !== "object") return false;
  return true;
}

/** Same prefix scan as getByPrefix but returns key + value (needed to recover vendor id from key). */
export const getByPrefixWithKeys = async (
  prefix: string
): Promise<{ key: string; value: any }[]> => {
  const allRows: { key: string; value: any }[] = [];
  let offset = 0;

  for (;;) {
    const { data, error } = await withTimeout(
      supabaseClient
        .from("kv_store_16010b6f")
        .select("key, value")
        .like("key", prefix + "%")
        .order("key", { ascending: true })
        .range(offset, offset + PREFIX_PAGE_SIZE - 1),
      30000
    );
    if (error) {
      throw new Error(error.message);
    }
    const rows = data ?? [];
    for (const row of rows) {
      allRows.push({ key: row.key, value: row.value });
    }
    if (rows.length < PREFIX_PAGE_SIZE) {
      break;
    }
    offset += PREFIX_PAGE_SIZE;
  }

  return allRows;
};

/**
 * Vendor profile records only. getByPrefix("vendor:") incorrectly included vendor:audience:{vendorId}
 * (arrays), which the admin UI treated as empty vendor rows ("ghost" vendors).
 */
export const getVendorProfiles = async (): Promise<any[]> => {
  const rows = await getByPrefixWithKeys("vendor:");
  return rows
    .filter(({ key, value }) => isVendorProfileKvEntry(key, value))
    .map(({ key, value }) => {
      const idFromKey = key.slice("vendor:".length);
      const id = (value as any).id || idFromKey;
      return { ...(value as any), id };
    });
};

/** Targeted vendor-application lookup by email (avoids loading every application row). */
export const findVendorApplicationsByEmailNorm = async (
  emailNorm: string,
): Promise<any[] | null> => {
  const normalized = String(emailNorm || "").trim().toLowerCase();
  if (!normalized) return [];

  const { data, error } = await withTimeout(
    supabaseClient
      .from("kv_store_16010b6f")
      .select("value")
      .like("key", "vendor_application:%")
      .filter("value->>email", "ilike", normalized),
    8000,
  );

  if (error) {
    console.warn("findVendorApplicationsByEmailNorm:", error.message);
    return null;
  }

  return (data ?? [])
    .map((row) => row.value)
    .filter((value) => value != null && typeof value === "object");
};

/** Postgres RPC: paginated platform catalog (avoids loading all product:* rows into the edge). */
export async function rpcStorefrontCatalog(opts: {
  kind: "bootstrap" | "catalog";
  page: number;
  pageSize: number;
  category?: string | null;
  q?: string | null;
  sort?: string | null;
  minPrice?: number | null;
  maxPrice?: number | null;
}): Promise<Record<string, unknown> | null> {
  try {
    const { data, error } = await supabaseClient.rpc("rpc_storefront_catalog", {
      p_kind: opts.kind,
      p_page: opts.page,
      p_page_size: opts.pageSize,
      p_category: opts.category ?? null,
      p_q: opts.q ?? null,
      p_sort: opts.sort ?? "featured",
      p_min_price: opts.minPrice ?? null,
      p_max_price: opts.maxPrice ?? null,
    });
    if (error) {
      console.warn("rpc_storefront_catalog:", error.message);
      return null;
    }
    return data && typeof data === "object" ? (data as Record<string, unknown>) : null;
  } catch (e) {
    console.warn("rpc_storefront_catalog:", e);
    return null;
  }
}

/** Postgres RPC: paginated vendor storefront products (+ optional single-product slug resolve). */
export async function rpcVendorStorefrontProductsPage(opts: {
  vendorId: string;
  vendorBusinessName?: string | null;
  page: number;
  pageSize: number;
  category?: string | null;
  q?: string | null;
  resolveSlug?: string | null;
}): Promise<Record<string, unknown> | null> {
  try {
    const { data, error } = await supabaseClient.rpc("rpc_vendor_storefront_products_page", {
      p_vendor_id: opts.vendorId,
      p_vendor_business_name: opts.vendorBusinessName ?? null,
      p_page: opts.page,
      p_page_size: opts.pageSize,
      p_category: opts.category ?? null,
      p_q: opts.q ?? null,
      p_resolve_slug: opts.resolveSlug ?? null,
    });
    if (error) {
      console.warn("rpc_vendor_storefront_products_page:", error.message);
      return null;
    }
    return data && typeof data === "object" ? (data as Record<string, unknown>) : null;
  } catch (e) {
    console.warn("rpc_vendor_storefront_products_page:", e);
    return null;
  }
}