import { fetchVendorProducts } from "./module-cache";

const PIXEL_ID_RE = /^\d{5,20}$/;
const PURCHASE_DEDUPE_PREFIX = "meta-pixel-purchase:";
/** In-memory guard for rapid React re-renders / effect re-runs. */
const META_EVENT_DEDUPE_MS = 5000;

declare global {
  interface Window {
    fbq?: FbqFn;
    _fbq?: FbqFn;
    __migooMetaPixelState?: MetaPixelRuntimeState;
  }
}

type FbqFn = {
  (...args: unknown[]): void;
  callMethod?: (...args: unknown[]) => void;
  queue?: unknown[];
  loaded?: boolean;
  version?: string;
};

type MetaPixelRuntimeState = {
  activePixelId: string | null;
  recentEvents: Map<string, number>;
  pageViewTrackedPixels: Set<string>;
  hardenedPixelIds: Set<string>;
};

export function normalizeMetaPixelId(value: unknown): string {
  const raw = String(value ?? "")
    .replace(/[^\d]/g, "")
    .trim();
  return PIXEL_ID_RE.test(raw) ? raw : "";
}

let scriptRequested = false;
const serverMetaPixelState: MetaPixelRuntimeState = {
  activePixelId: null,
  recentEvents: new Map(),
  pageViewTrackedPixels: new Set(),
  hardenedPixelIds: new Set(),
};

function getMetaPixelState(): MetaPixelRuntimeState {
  if (typeof window === "undefined") return serverMetaPixelState;
  if (!window.__migooMetaPixelState) {
    window.__migooMetaPixelState = {
      activePixelId: null,
      recentEvents: new Map(),
      pageViewTrackedPixels: new Set(),
      hardenedPixelIds: new Set(),
    };
  }
  return window.__migooMetaPixelState;
}

function applyMetaPixelHardening(pixelId: string): void {
  const id = normalizeMetaPixelId(pixelId);
  const state = getMetaPixelState();
  if (
    !id ||
    typeof window === "undefined" ||
    state.hardenedPixelIds.has(id)
  ) {
    return;
  }
  // Force-disable Meta automatic event discovery from code so random button clicks
  // (e.g. "SubscribedButtonClick") are not auto-generated by the browser pixel.
  window.fbq?.("set", "autoConfig", false, id);
  state.hardenedPixelIds.add(id);
}

function shouldFireMetaEvent(eventKey: string): boolean {
  const now = Date.now();
  const state = getMetaPixelState();
  const scopedEventKey = `${state.activePixelId || "none"}:${eventKey}`;
  const last = state.recentEvents.get(scopedEventKey);
  if (last != null && now - last < META_EVENT_DEDUPE_MS) {
    return false;
  }
  state.recentEvents.set(scopedEventKey, now);
  return true;
}

function loadFbeventsScript(): void {
  if (typeof window === "undefined" || scriptRequested) return;
  scriptRequested = true;

  if (!window.fbq) {
    const n = function (this: FbqFn, ...args: unknown[]) {
      if (n.callMethod) {
        n.callMethod(...args);
      } else {
        n.queue?.push(args);
      }
    } as FbqFn;
    n.queue = [];
    n.loaded = true;
    n.version = "2.0";
    window.fbq = n;
    window._fbq = n;
    const script = document.createElement("script");
    script.async = true;
    script.src = "https://connect.facebook.net/en_US/fbevents.js";
    document.head.appendChild(script);
  }
}

/** Load pixel script and call `fbq('init', id)`. Returns false when id is invalid. */
export function initMetaPixel(pixelId: string): boolean {
  const id = normalizeMetaPixelId(pixelId);
  if (!id || typeof window === "undefined") return false;

  loadFbeventsScript();
  const state = getMetaPixelState();
  if (state.activePixelId !== id) {
    applyMetaPixelHardening(id);
    // Disable Meta's automatic PageView on init — PageView is tracked explicitly.
    window.fbq?.("init", id, {}, { autoConfig: false });
    state.activePixelId = id;
  }
  return true;
}

export function getActiveMetaPixelId(): string | null {
  return getMetaPixelState().activePixelId;
}

export function trackMetaPageView(pathname?: string): void {
  const state = getMetaPixelState();
  if (
    !state.activePixelId ||
    state.pageViewTrackedPixels.has(state.activePixelId)
  ) {
    return;
  }
  state.pageViewTrackedPixels.add(state.activePixelId);
  const pagePath = String(pathname || "").trim();
  if (pagePath) {
    window.fbq?.("track", "PageView", { page_path: pagePath });
    return;
  }
  window.fbq?.("track", "PageView");
}

export function trackMetaViewContent(product: {
  id: string;
  name: string;
  price?: number;
  currency?: string;
}): void {
  if (!getMetaPixelState().activePixelId) return;
  const key = `ViewContent:${product.id}`;
  if (!shouldFireMetaEvent(key)) return;
  window.fbq?.("track", "ViewContent", {
    content_ids: [product.id],
    content_name: product.name,
    content_type: "product",
    value: product.price,
    currency: product.currency || "MMK",
  });
}

export function trackMetaAddToCart(item: {
  id: string;
  sku?: string;
  name: string;
  price: number;
  quantity: number;
  currency?: string;
}): void {
  if (!getMetaPixelState().activePixelId) return;
  const sku = String(item.sku || "").trim();
  const value = Math.round((Number(item.price) || 0) * (Number(item.quantity) || 1));
  const key = `AddToCart:${item.id}:${sku}:${Math.max(1, Number(item.quantity) || 1)}:${value}`;
  if (!shouldFireMetaEvent(key)) return;
  window.fbq?.("track", "AddToCart", {
    content_ids: [item.id],
    content_name: item.name,
    content_type: "product",
    value,
    currency: item.currency || "MMK",
  });
}

export function trackMetaBuyNow(item: {
  id: string;
  sku?: string;
  name: string;
  price: number;
  quantity: number;
  currency?: string;
}): void {
  if (!getMetaPixelState().activePixelId) return;
  const sku = String(item.sku || "").trim();
  const quantity = Math.max(1, Number(item.quantity) || 1);
  const value = Math.round((Number(item.price) || 0) * quantity);
  const key = `BuyNow:${item.id}:${sku}:${quantity}:${value}`;
  if (!shouldFireMetaEvent(key)) return;
  window.fbq?.("trackCustom", "BuyNow", {
    content_ids: [item.id],
    content_name: item.name,
    content_type: "product",
    num_items: quantity,
    value,
    currency: item.currency || "MMK",
  });
}

export function trackMetaSearch(searchString: string): void {
  if (!getMetaPixelState().activePixelId) return;
  const query = String(searchString || "").trim();
  if (!query) return;
  const key = `Search:${query.toLocaleLowerCase()}`;
  if (!shouldFireMetaEvent(key)) return;
  window.fbq?.("track", "Search", {
    search_string: query,
  });
}

export function trackMetaCategoryFilter(category: string): void {
  if (!getMetaPixelState().activePixelId) return;
  const name = String(category || "").trim();
  if (!name || name.toLocaleLowerCase() === "all") return;
  const key = `FilterByCategory:${name.toLocaleLowerCase()}`;
  if (!shouldFireMetaEvent(key)) return;
  window.fbq?.("trackCustom", "FilterByCategory", {
    content_category: name,
  });
}

export function trackMetaInitiateCheckout(
  items: Array<{ id: string; quantity: number }>,
  value: number,
  currency = "MMK"
): void {
  if (!getMetaPixelState().activePixelId) return;
  const linesKey = items.map((i) => `${i.id}x${i.quantity}`).join(",");
  const key = `InitiateCheckout:${Math.round(value)}:${linesKey}`;
  if (!shouldFireMetaEvent(key)) return;
  window.fbq?.("track", "InitiateCheckout", {
    content_ids: items.map((i) => i.id),
    num_items: items.reduce((n, i) => n + i.quantity, 0),
    value,
    currency,
  });
}

export function trackMetaPurchaseOnce(order: {
  orderId: string;
  value: number;
  items: Array<{ id: string; quantity: number }>;
  currency?: string;
}): void {
  if (!getMetaPixelState().activePixelId) return;
  const orderId = String(order.orderId || "").trim();
  if (!orderId) return;

  const dedupeKey = `${PURCHASE_DEDUPE_PREFIX}${orderId}`;
  try {
    if (sessionStorage.getItem(dedupeKey)) return;
    sessionStorage.setItem(dedupeKey, "1");
  } catch {
    /* private mode — still attempt one fire per page load */
  }

  window.fbq?.(
    "track",
    "Purchase",
    {
      content_ids: order.items.map((i) => i.id),
      content_type: "product",
      value: order.value,
      currency: order.currency || "MMK",
      order_id: orderId,
    },
    { eventID: orderId }
  );
}

/** Resolve pixel id from prop or vendor catalog API, then init. */
export async function ensureMetaPixelForVendor(
  vendorId: string,
  pixelIdHint?: string | null
): Promise<string> {
  const fromHint = normalizeMetaPixelId(pixelIdHint);
  if (fromHint) {
    initMetaPixel(fromHint);
    return fromHint;
  }

  const vid = String(vendorId || "").trim();
  if (!vid) return "";

  try {
    const data = await fetchVendorProducts(vid, { page: 1, pageSize: 1 });
    const id = normalizeMetaPixelId(data.metaPixelId);
    if (id) initMetaPixel(id);
    return id;
  } catch {
    return "";
  }
}

export function applyMetaPixelIdFromPayload(
  current: string | undefined,
  payload: { metaPixelId?: string | null } | null | undefined
): string | undefined {
  const next = normalizeMetaPixelId(payload?.metaPixelId);
  if (next) return next;
  return current;
}
