/** Myanmar Burmese labels for checkout location selects. */

export const MYANMAR_REGION_LABELS_MY = {
  "Yangon": "ရန်ကုန်တိုင်းဒေသကြီး",
  "Mandalay": "မန္တလေးတိုင်းဒေသကြီး",
  "Naypyidaw": "နေပြည်တော်",
  "Ayeyarwady": "ဧရာဝတီတိုင်းဒေသကြီး",
  "Bago": "ပဲခူးတိုင်းဒေသကြီး",
  "Chin": "ချင်းပြည်နယ်",
  "Kachin": "ကချင်ပြည်နယ်",
  "Kayah": "ကယားပြည်နယ်",
  "Kayin": "ကရင်ပြည်နယ်",
  "Magway": "မကွေးတိုင်းဒေသကြီး",
  "Mon": "မွန်ပြည်နယ်",
  "Rakhine": "ရခိုင်ပြည်နယ်",
  "Sagaing": "စစ်ကိုင်းတိုင်းဒေသကြီး",
  "Shan": "ရှမ်းပြည်နယ်",
  "Tanintharyi": "တနင်္သာရီတိုင်းဒေသကြီး",
} as const;

export const MYANMAR_TOWNSHIP_LABELS_MY = {
  "Ahlone": "အလုံ",
  "Ahmar": "အမာ",
  "Ahpyauk": "အဖျောက်",
  "Ahtaung": "အထောင်",
  "Ahthoke": "အသုတ်",
  "Amarapura": "အမရပူရ",
  "Ann": "အမ်း",
  "Aunglan": "အောင်လံ",
  "Aungmyaythazan": "အောင်မြေသာဇံ",
  "Aungpan": "အောင်ပန်း",
  "Ayadaw": "အရာတော်",
  "Ayetharyar": "အေးသာယာ",
  "Bagan": "ပုဂံ",
  "Bago": "ပဲခူး",
  "Bahan": "ဗဟန်း",
  "Banmauk": "ဗန်းမောက်",
  "Batye": "ဘက်ရဲ",
  "Baw Ga Li": "ဘောဂလိ",
  "Bawlakhe": "ဘောလခဲ",
  "Bhamo": "ဗန်းမော်",
  "Bilin": "ဘီးလင်း",
  "Bogale": "ဘိုကလေး",
  "Bokpyin": "ဘုတ်ပြင်း",
  "Botataung": "ဗိုလ်တထောင်",
  "Budalin": "ဘုတလင်",
  "Buthidaung": "ဘူးသီးတောင်",
  "Chanayethazan": "ချမ်းအေးသာဇံ",
  "Chanmyathazi": "ချမ်းမြသာစည်",
  "Chauk": "ချောက်",
  "Chaung Thar": "ချောင်းသာ",
  "Chaung-U": "ချောင်းဦး",
  "Chaungzon": "ချောင်းဆုံ",
  "Chinshwehaw": "ချင်းရွှေဟော်",
  "Chipwi": "ချီဖွေ",
  "Cikha": "ကျီခါး",
  "Cocokyun": "ကိုကိုးကျွန်း",
  "Dagon": "ဒဂုံ",
  "Dagon Myothit (East)": "ဒဂုံမြို့သစ် (အရှေ့ပိုင်း)",
  "Dagon Myothit (North)": "ဒဂုံမြို့သစ်(မြောက်ပိုင်း)",
  "Dagon Myothit (Seikkan)": "ဒဂုံမြို့သစ် (ဆိပ်ကမ်း)",
  "Dagon Myothit (South)": "ဒဂုံမြို့သစ်(တောင်ပိုင်း)",
  "Daik-U": "ဒိုက်ဦး",
  "Dala": "ဒလ",
  "Danubyu": "ဓနုဖြူ",
  "Dawbon": "ဒေါပုံ",
  "Dawei": "ထားဝယ်",
  "Dawthponeyan": "ဒေါ့ဖုန်းယန်",
  "Dedaye": "ဒေးဒရဲ",
  "Dekkhinathiri": "ဒက္ခိဏသီရိ",
  "Demoso": "ဒီးမော့ဆို",
  "Du Yar": "ဒူးယား",
  "East Dagon": "အရှေ့ဒဂုံ",
  "Einme": "အိမ်မဲ",
  "Falam": "ဖလမ်း",
  "Gangaw": "ဂန့်ဂေါ",
  "Gwa": "ဂွ",
  "Gyobingauk": "ကြို့ပင်ကောက်",
  "Hainggyikyun": "ဟိုင်းကြီးကျွန်း",
  "Hakha": "ဟားခါး",
  "He Hoe": "ဟဲဟိုး",
  "Hinthada": "ဟင်္သာတ",
  "Hkamti": "ခန္တီး",
  "Hlaing": "လှိုင်",
  "Hlaingbwe": "လှိုင်းဘွဲ့",
  "Hlaingthaya": "လှိုင်သာယာ",
  "Hlaingthaya (East)": "လှိုင်သာယာ (အရှေ့ပိုင်း)",
  "Hlaingthaya (West)": "လှိုင်သာယာ (အနောက်ပိုင်း)",
  "Hlegu": "လှည်းကူး",
  "Hmawbi": "မှော်ဘီ",
  "Hmone Hta": "မုံးထ",
  "Hnaring": "နှာဟရိန်",
  "Homalin": "ဟုမ္မလင်း",
  "Homein": "ဟိုမိန်း",
  "Hopang": "ဟိုပန်",
  "Hopin": "ဟိုပင်",
  "Hopong": "ဟိုပုံး",
  "Hpa Do": "ဖဒို",
  "Hpa-An": "ဘားအံ",
  "Hpakant": "ဖားကန့်",
  "Hpapun": "ဖာပွန်",
  "Hpasawng": "ဖားဆောင်း",
  "Hpayargyi": "ဘုရားကြီး",
  "Hpayarthonesu": "ဘုရားသုံးဆူ",
  "Hpruso": "ဖရူဆို",
  "Hseni": "သိန္နီ",
  "Hsihseng": "ဆီဆိုင်",
  "Hsipaw": "သီပေါ",
  "Hswar": "ဆွာ",
  "Htantabin": "ထန်းတပင်",
  "Htaukkyant": "ထောက်ကြန့်",
  "Htoogyi": "ထူးကြီး",
  "In Pin": "အင်ပင်",
  "Indaw": "အင်းတော်",
  "Ingapu": "အင်္ဂပူ",
  "Injangyang": "အင်ဂျန်းယန်",
  "Inn Ma": "အင်းမ",
  "Inn Taw Gyi": "အင်းတော်ကြီး",
  "Inntakaw": "အင်းတကော်",
  "Insein": "အင်းစိန်",
  "Intaw": "အင်တော",
  "Kalaw": "ကလော",
  "Kale": "ကလေး",
  "Kaleinaung": "ကလိန်အောင်",
  "Kalewa": "ကလေးဝ",
  "Kamaing": "ကာမိုင်း",
  "Kamarmaung": "ကမမောင်း",
  "Kamarwet": "ကမာ၀က်",
  "Kamayut": "ကမာရွတ်",
  "Kamma": "ကံမ",
  "Kamma (PKU)": "ကမ္မ",
  "Kan Paik Ti": "ကန်ပိုက်တီ",
  "Kanaung": "ကနောင်",
  "Kanbalu": "ကန့်ဘလူ",
  "Kangyidaunt": "ကန်ကြီးထောင့်",
  "Kanhtauntkyi": "ကမ်းထောင့်ကြီး",
  "Kani": "ကနီ",
  "Kanpetlet": "ကန်ပက်လက်",
  "Kanyutkwin": "ကညွတ်ကွင်း",
  "Kar Li": "ကာလိ",
  "Karathuri": "ကရသူရိ",
  "Katha": "ကသာ",
  "Kawa": "ကဝ",
  "Kawhmu": "ကော့မှူး",
  "Kawkareik": "ကော့ကရိတ်",
  "Kawlin": "ကောလင်း",
  "Kawthoung": "ကော့သောင်း",
  "Kayan": "ခရမ်း",
  "Kaytumati": "ကေတုမတီ",
  "Kenglat": "ကျိုင်းလပ်",
  "Kengtawng": "ကျိုင်းတောင်း",
  "Kengtung": "ကျိုင်းတုံ",
  "Kengtung (Kyinetone)": "ကျိုင်းတုံ",
  "Kha Maung Seik": "ခမောင်းဆိပ်",
  "Khaikam": "ခိုင်ကမ်း",
  "Khamaukgyi": "ခမောက်ကြီး",
  "Khampat": "ခါမ်းပါတ်",
  "Khaunglanhpu": "ခေါင်လန်ဖူး",
  "Khawzar": "ခေါဇာ",
  "Khin-U": "ခင်ဦး",
  "Kho Lam": "ခိုလမ်",
  "Konkyan": "ကုန်းကြမ်း",
  "Ku Me": "ကူမဲ",
  "Kungyangon": "ကွမ်းခြံကုန်း",
  "Kunhing": "ကွန်ဟိန်း",
  "Kunlong": "ကွမ်းလုံ",
  "Kutkai": "ကွတ်ခိုင်",
  "Kyaikdon": "ကျိုက်ဒုံ",
  "Kyaikkhami": "ကျိုက္ခမီ",
  "Kyaiklat": "ကျိုက်လတ်",
  "Kyaikmaraw": "ကျိုက်မရော",
  "Kyaikto": "ကျိုက်ထို",
  "Kyainseikgyi": "ကြာအင်းဆိပ်ကြီး",
  "Kyangin": "ကြံခင်း",
  "Kyaukhtu": "ကျောက်ထု",
  "Kyaukkyi": "ကျောက်ကြီး",
  "Kyaukme": "ကျောက်မဲ",
  "Kyaukpadaung": "ကျောက်ပန်းတောင်း",
  "Kyaukpyu": "ကျောက်ဖြူ",
  "Kyaukse": "ကျောက်ဆည်",
  "Kyauktada": "ကျောက်တံတား",
  "Kyauktaga": "ကျောက်တံခါး",
  "Kyauktalonegyi": "ကျောက်တလုံးကြီး",
  "Kyauktan": "ကျောက်တန်း",
  "Kyauktaw": "ကျောက်တော်",
  "Kyauk Myaung": "ကျောက်မြောင်",
  "Kyaunggon": "ကျောင်းကုန်း",
  "Kyaw": "ကျော",
  "Kyeintali": "ကျိန္တလီ",
  "Kyethi": "ကျေးသီး",
  "Kyimyindaing": "ကြည့်မြင်တိုင်",
  "Kyin Dway": "ကျင်ဒွေး",
  "Kyondoe": "ကျုံဒိုး",
  "Kyonmangae": "ကျုံမငေး",
  "Kyonpyaw": "ကျုံပျော်",
  "Kyunhla": "ကျွန်းလှ",
  "Kyunsu": "ကျွန်းစု",
  "Kywe Pwe": "ကျွဲပွဲ",
  "Labutta": "လပွတ္တာ",
  "Labutta (3) Mile": "လပွတ္တာ (၃) မိုင်",
  "Laihka": "လဲချား",
  "Lalengpi": "လိုင်လင်းပီ",
  "Lamaing": "လမိုင်း",
  "Langkho": "လင်းခေး",
  "Lanmadaw": "လမ်းမတော်",
  "Lashio": "လားရှိုး",
  "Latha": "လသာ",
  "Laukkaing": "လောက်ကိုင်",
  "Launglon": "လောင်းလုံး",
  "Lawksawk": "ရပ်စောက်",
  "Lawksawk (Yetsauk)": "ရပ်စောက်",
  "Lay Taung": "လေးတောင်",
  "Leik Tho": "လိပ်သို",
  "Lemyethna": "လေးမျက်နှာ",
  "Letpadan": "လက်ပံတန်း",
  "Lewe": "လယ်ဝေး",
  "Loikaw": "လွိုင်ကော်",
  "Loilen": "လွိုင်လင်",
  "Loilen Lay": "လွိုင်လင်လေး",
  "Lwegel": "လွယ်ဂျယ်",
  "M'kuiimnu": "မကွီအိမ်နူး",
  "Ma-Ei": "မအီ",
  "Mabein": "မဘိမ်း",
  "Machanbaw": "မချမ်းဘော",
  "Madauk": "မဒေါက်",
  "Madaya": "မတ္တရာ",
  "Magway": "မကွေး",
  "Mahaaungmyay": "မဟာအောင်မြေ",
  "Mahlaing": "မလှိုင်",
  "Man Kan": "မန်ကန်",
  "Manhlyoe (Manhero)": "(မန်ဟျိုး) မန်ဟီးရိုး",
  "Mansi": "မံစီ",
  "Manton": "မန်တုံ",
  "Matman": "မက်မန်း",
  "Matupi": "မတူပီ",
  "Maubin": "မအူပင်",
  "Maungdaw": "မောင်တော",
  "Maw Lu": "မော်လူး",
  "Maw Hteik": "မော်ထိပ်",
  "Maw Taung": "မောတောင်",
  "Mawkmai": "မောက်မယ်",
  "Mawlaik": "မော်လိုက်",
  "Mawlamyine": "မော်လမြိုင်",
  "Mawlamyinegyun": "မော်လမြိုင်ကျွန်း",
  "Mayangon": "မရမ်းကုန်း",
  "Me Za Li Kone": "မဲဇလီကုန်း",
  "Meiktila": "မိတ္ထီလာ",
  "Mese": "မယ်စဲ",
  "Minbu": "မင်းဘူး",
  "Minbya": "မင်းပြား",
  "Mindat": "မင်းတပ်",
  "Mindon": "မင်းတုန်း",
  "Mingala Taungnyunt": "မင်္ဂလာတောင်ညွန့်",
  "Mingaladon": "မင်္ဂလာဒုံ",
  "Mingin": "မင်းကင်း",
  "Minhla": "မင်းလှ",
  "Mogaung": "မိုးကောင်း",
  "Mogok": "မိုးကုတ်",
  "Mohnyin": "မိုးညှင်း",
  "Momauk": "မိုးမောက်",
  "Monekoe": "မုန်းကိုး",
  "Monghpyak": "မိုင်းဖြတ်",
  "Monghsat": "မိုင်းဆတ်",
  "Monghsu": "မိုင်းရှူး",
  "Mongkaing": "မိုင်းကိုင်",
  "Mongkhet": "မိုင်းခတ်",
  "Mongkhoke": "မိုင်းခုတ်",
  "Mongla": "မိုင်းလား",
  "Monglon": "မိုင်းလုံ",
  "Mongmao": "မိုင်းမော",
  "Mongmit": "မိုးမိတ်",
  "Mongnai": "မိုးနဲ",
  "Mongnai (Moenae)": "မိုးနဲ",
  "Mongnawng": "မိုင်းနောင်",
  "Mongngawt": "မိုင်းငေါ့",
  "Mongpan": "မိုင်းပန်",
  "Mongping": "မိုင်းပျဉ်း",
  "Mongsan (Hmonesan)": "မိုင်းစံ (မုန်းဆန်း)",
  "Mongton": "မိုင်းတုံ",
  "Mongyai": "မိုင်းရယ်",
  "Mongyang": "မိုင်းယန်း",
  "Mongyawng": "မိုင်းယောင်း",
  "Mongyu": "မိုင်းယု",
  "Monyo": "မိုးညို",
  "Monywa": "မုံရွာ",
  "Mrauk-U": "မြောက်ဦး",
  "Mudon": "မုဒုံ",
  "Munaung": "မာန်အောင်",
  "Muse": "မူဆယ်",
  "Myaing": "မြိုင်",
  "Myanaung": "မြန်အောင်",
  "Myaung": "မြောင်",
  "Myaungmya": "မြောင်းမြ",
  "Myawaddy": "မြဝတီ",
  "Myebon": "မြေပုံ",
  "Myeik": "မြိတ်",
  "Myin Hlut": "မြင်းလွှတ်",
  "Myingyan": "မြင်းခြံ",
  "Myinmu": "မြင်းမူ",
  "Myit Chay": "မြစ်ခြေ",
  "Myitkyina": "မြစ်ကြီးနား",
  "Myitnge": "မြစ်ငယ်",
  "Myitta": "မေတ္တာ",
  "Myittha": "မြစ်သား",
  "Myo Hla": "မြို့လှ",
  "Myothit": "မြို့သစ်",
  "Nam Mar": "နန်းမား",
  "Nam Mun": "နန့်မွန်း",
  "Nam Tit": "နမ့်တစ်",
  "Namhkan": "နမ့်ခမ်း",
  "Namhsan": "နမ့်ဆန်",
  "Namphan": "နားဖန်",
  "Nammatee": "နမ္မတီး",
  "Namtu": "နမ္မတူ",
  "Nan Mei Khon": "နန်းမယ်ခုံ",
  "Nang Pang": "နန်းပန်",
  "Nansang": "နမ့်စန်",
  "Nansang (South)": "နမ့်စန်",
  "Nyaungchedauk": "ညောင်ချေတောက်",
  "Natmauk": "နတ်မောက်",
  "Natogyi": "နွားထိုးကြီး",
  "Nattalin": "နတ်တလင်း",
  "Naungtayar": "နောင်တရား",
  "Nawnghkio": "နောင်ချို",
  "Nawnghkio (Naungcho)": "နောင်ချို",
  "Nawngmun": "နောင်မွန်း",
  "Ngapali": "ငပလီ",
  "Ngape": "ငဖဲ",
  "Ngapudaw": "ငပုတော",
  "Ngathaingchaung": "ငသိုင်းချောင်း",
  "Ngathayauk": "ငါ့သရောက်",
  "Ngayokekaung": "ငရုတ်ကောင်း",
  "Ngazun": "ငါန်းဇွန်",
  "Ngwesaung": "ငွေဆောင်",
  "North Dagon": "မြောက်ဒဂုံ",
  "North Okkalapa": "မြောက်ဥက္ကလာပ",
  "Nyaung-U": "ညောင်ဦး",
  "Nyaungdon": "ညောင်တုန်း",
  "Nyaunglebin": "ညောင်လေးပင်",
  "Nyaungshwe": "ညောင်ရွှေ",
  "Oakshitpin": "ဥရှစ်ပင်",
  "Oe Thei Kone": "အိုးသည်ကုန်း",
  "Okekan": "ဥက္ကံ",
  "Okpho": "အုတ်ဖို",
  "Oktwin": "အုတ်တွင်း",
  "Ottarathiri": "ဥတ္တရသီရိ",
  "Pabedan": "ပန်းဘဲတန်း",
  "Padaung": "ပန်းတောင်း",
  "Paingkyon": "ပိုင်ကျုံ",
  "Pakokku": "ပခုက္ကူ",
  "Pala": "ပလ",
  "Palauk": "ပလောက်",
  "Palaw": "ပုလော",
  "Pale": "ပုလဲ",
  "Paletwa": "ပလက်ဝ",
  "Pan Lon": "ပန်လုံ",
  "Pang Hseng (Kyu Koke)": "ပန်ဆိုင်း (ကြူကုတ်)",
  "Pang War": "ပန်ဝါ",
  "Pangsang (Panghkam)": "ပန်ဆန်း (ပန်ခမ်း)",
  "Pannandin": "ပန်နန်းဒင်",
  "Pantanaw": "ပန်းတနော်",
  "Pathein": "ပုသိမ်",
  "Patheingyi": "ပုသိမ်ကြီး",
  "Pauk": "ပေါက်",
  "Paukkhaung": "ပေါက်ခေါင်း",
  "Pauktaw": "ပေါက်တော",
  "Paung": "ပေါင်",
  "Paungbyin": "ဖောင်းပြင်",
  "Paungdale": "ပေါင်းတလည်",
  "Paungde": "ပေါင်းတည်",
  "Pawng Lawng": "ပေါင်းလောင်း",
  "Pazundaung": "ပုဇွန်တောင်",
  "Peinzalok": "ပိန်းဇလုပ်",
  "Pekon": "ဖယ်ခုံ",
  "Penwegon": "ပဲနွယ်ကုန်း",
  "Phyu": "ဖြူး",
  "Pindaya": "ပင်းတယ",
  "Pinlaung": "ပင်လောင်း",
  "Pinlebu": "ပင်လည်ဘူး",
  "Pinlon": "ပင်လုံ",
  "Poke Ba Thi Ri": "ပုဗ္ဗသီရိ",
  "Ponnagyun": "ပုဏ္ဏားကျွန်း",
  "Ponparkyin": "ပုံပါကျင်",
  "Putao": "ပူတာအို",
  "Puteekone": "ပုတီးကုန်း",
  "Pwintbyu": "ပွင့်ဖြူ",
  "Pyapon": "ဖျာပုံ",
  "Pyawbwe": "ပျော်ဘွယ်",
  "Pyay": "ပြည်",
  "Pyigyimandaing": "ပြည်ကြီးမဏ္ဍိုင်",
  "Pyigyitagun": "ပြည်ကြီးတံခွန်",
  "Pyin Oo Lwin": "ပြင်ဦးလွင်",
  "Pyinmana": "ပျဉ်းမနား",
  "Pyinsalu": "ပြင်စလူ",
  "Pyuntasa": "ပြွန်တန်ဆာ",
  "Ramree": "ရမ်းဗြဲ",
  "Rathedaung": "ရသေ့တောင်",
  "Rezua": "ရေဇွာ",
  "Rihkhawdar": "ရိခေါ်ဒါရ်",
  "Sa Lay": "စလေ",
  "Sa Ne": "စနဲ",
  "Sadung": "ဆဒုံး",
  "Sagaing": "စစ်ကိုင်း",
  "Saing Pyin": "စိုင်ပြင်",
  "Saku": "စကု",
  "Salin": "စလင်း",
  "Salingyi": "ဆားလင်းကြီး",
  "Samee": "ဆမီး",
  "Sanchaung": "စမ်းချောင်း",
  "Sar Taung": "ဆားတောင်",
  "Saw": "ဆော",
  "Seikgyi Kanaungto": "ဆိပ်ကြီး/ခနောင်တို",
  "Seikphyu": "ဆိပ်ဖြူ",
  "Shadaw": "ရှားတော",
  "Shan Ywar Thit": "ရှမ်းရွာသစ်",
  "Shin Bway Yang": "ရှင်ဗွေယန်",
  "Shwe Pyi Aye": "ရွှေပြည်အေး",
  "Shwebo": "ရွှေဘို",
  "Shwedaung": "ရွှေတောင်",
  "Shwegu": "ရွှေကူ",
  "Shwegyin": "ရွှေကျင်",
  "Shwenyaung": "ရွှေညောင်",
  "Shwe Paunt Kan": "ရွှေပေါက်ကံ",
  "Shwepyithar": "ရွှေပြည်သာ",
  "Shwethaungyan": "ရွှေသောင်ယံ",
  "Si Mee Khon": "ဆီမီးခုံ",
  "Sidoktaya": "စေတုတ္ထရာ",
  "Sin Mee Swea": "ဆင်မြီးဆွဲ",
  "Sinbaungwe": "ဆင်ပေါင်ဝဲ",
  "Sinbo": "ဆင်ဘို",
  "Singu": "စဉ့်ကူး",
  "Sinphyukyun": "ဆင်ဖြူကျွန်း",
  "Sintgaing": "စဉ့်ကိုင်",
  "Sit Kwin": "စစ်ကွင်း",
  "Sittwe": "စစ်တွေ",
  "South Dagon": "ဒဂုံမြို့သစ်(တောင်ပိုင်း)",
  "South Okkalapa": "တောင်ဥက္ကလာပ",
  "Su Ka Li": "စုကလိ",
  "Sumprabum": "ဆွမ်ပရာဘွမ်",
  "Surkhua": "ဆူရ်ခွား",
  "Ta Loke Htaw": "တလုတ္ထော်",
  "Tabayin": "ဒီပဲယင်း",
  "Tachileik": "တာချီလိတ်",
  "Tada-U": "တံတားဦး",
  "Tadar": "တံတား",
  "Taikkyi": "တိုက်ကြီး",
  "Takaung": "တကောင်း",
  "Tamu": "တမူး",
  "Tamwe": "တာမွေ",
  "Tan Hlwe Ywar Ma": "တန်းလွဲရွာမ",
  "Tanai": "တနိုင်း",
  "Tangyan": "တန့်ယန်း",
  "Tanintharyi": "တနင်္သာရီ",
  "Tar Pun": "တာပွန်",
  "Tarlay": "တာလေ",
  "Tarmoenye": "တာမိုးညဲ",
  "Tat Taung": "တပ်တောင်",
  "Tatkon": "တပ်ကုန်း",
  "Taungdwingyi": "တောင်တွင်းကြီး",
  "Taunggyi": "တောင်ကြီး",
  "Taungoo": "တောင်ငူ",
  "Taungpyoletwea": "တောင်ပြိုလက်ဝဲ",
  "Taungtha": "တောင်သာ",
  "Taungup": "တောင်ကုတ်",
  "Taze": "တန့်ဆည်",
  "Tedim": "တီးတိန်",
  "Thabaung": "သာပေါင်း",
  "Thabeikkyin": "သပိတ်ကျင်း",
  "Thaketa": "သာကေတ",
  "Thanatpin": "သနပ်ပင်",
  "Thanbyuzayat": "သံဖြူဇရပ်",
  "Thandaung": "သံတောင်",
  "Thandaunggyi": "သံတောင်ကြီး",
  "Thandwe": "သံတွဲ",
  "Thanlyin": "သန်လျင်",
  "Thantlang": "ထန်တလန်",
  "Thaton": "သထုံ",
  "Thayarwady": "သာယာဝတီ",
  "Thayet": "သရက်",
  "Thayetchaung": "သရက်ချောင်း",
  "Thazi": "သာစည်",
  "Thegon": "သဲကုန်း",
  "Thein Za Yat": "သိမ်ဇရပ်",
  "Thetkala": "သက္ကလ",
  "Thingangyun": "သင်္ဃန်းကျွန်း",
  "Thongwa": "သုံးခွ",
  "Thonse": "သုံးဆယ်",
  "Thuwunnawady": "သုဝဏ္ဏဝတီ",
  "Tigyaing": "ထီးချိုင့်",
  "Tilin": "ထီးလင်း",
  "Tontar": "တုံတာ",
  "Tonzang": "တွန်းဇန်",
  "Tsawlaw": "ဆော့လော်",
  "Twantay": "တွံတေး",
  "Waingmaw": "ဝိုင်းမော်",
  "Wakema": "ဝါးခယ်မ",
  "Waw Lay Myaing (Waw Lay)": "ဝေါလေးမြိုင် (ဝေါလေး)",
  "Waw": "ဝေါ",
  "Webula": "ဝေဘူလ",
  "Wetlet": "ဝက်လက်",
  "Wundwin": "ဝမ်းတွင်း",
  "Wuntho": "ဝန်းသို",
  "Yae Ni": "ရေနီ",
  "Yamethin": "ရမည်းသင်း",
  "Yuzana Oo Yin": "ယုဇနအူယင်",
  "Yankin": "ရန်ကင်း",
  "Ye": "ရေး",
  "Ye-U": "ရေဦး",
  "Yebyu": "ရေဖြူ",
  "Yedashe": "ရေတာရှည်",
  "Yegyi": "ရေကြည်",
  "Yenangyaung": "ရေနံချောင်း",
  "Yesagyo": "ရေစကြို",
  "Yinmarbin": "ယင်းမာပင်",
  "Ywangan": "ရွာငံ",
  "Ywarthit": "ရွာသစ်",
  "Zabuthiri": "ဇမ္ဗူသီရိ",
  "Zalun": "ဇလွန်",
  "Zayyawadi": "ဇေယျ၀တီ",
  "Zee Kone": "ဇီးကုန်း",
  "Zeyarthiri": "ဇေယျာသီရိ",
  "Zigon": "ဇီးကုန်း",
  "Zinkyaik": "ဇင်းကျိုက်",
} as const;

