/** Myanmar Burmese labels for checkout location selects. */

export const MYANMAR_REGION_LABELS_MY = {
  "Yangon": "ရန်ကုန်တိုင်းဒေသကြီး",
  "Mandalay": "မန္တလေးတိုင်းဒေသကြီး",
  "Naypyidaw": "နေပြည်တော်",
  "Ayeyarwady": "ဧရာဝတီတိုင်းဒေသကြီး",
  "Bago": "ပဲခူးတိုင်းဒေသကြီး",
  "Chin": "ချင်းပြည်နယ်",
  "Kachin": "ကချင်ပြည်နယ်",
  "Kayah": "ကယားပြည်နယ်",
  "Kayin": "ကရင်ပြည်နယ်",
  "Magway": "မကွေးတိုင်းဒေသကြီး",
  "Mon": "မွန်ပြည်နယ်",
  "Rakhine": "ရခိုင်ပြည်နယ်",
  "Sagaing": "စစ်ကိုင်းတိုင်းဒေသကြီး",
  "Shan": "ရှမ်းပြည်နယ်",
  "Tanintharyi": "တနင်္သာရီတိုင်းဒေသကြီး",
} as const;

export const MYANMAR_TOWNSHIP_LABELS_MY = {
  "Ahlone": "အလုံ",
  "Bahan": "ဗဟန်း",
  "Botataung": "ဗိုလ်တထောင်",
  "Cocokyun": "ကိုကိုးကျွန်း",
  "Dagon": "ဒဂုံ",
  "Dagon Myothit (East)": "ဒဂုံမြို့သစ် (အရှေ့ပိုင်း)",
  "Dagon Myothit (North)": "ဒဂုံမြို့သစ်(မြောက်ပိုင်း)",
  "Dagon Myothit (Seikkan)": "ဒဂုံမြို့သစ် (ဆိပ်ကမ်း)",
  "Dagon Myothit (South)": "ဒဂုံမြို့သစ်(တောင်ပိုင်း)",
  "Dala": "ဒလ",
  "Dawbon": "ဒေါပုံ",
  "East Dagon": "အရှေ့ဒဂုံ",
  "Hlaing": "လှိုင်",
  "Hlaingthaya": "လှိုင်သာယာ",
  "Insein": "အင်းစိန်",
  "Kamayut": "ကမာရွတ်",
  "Kawhmu": "ကော့မှူး",
  "Kayan": "ခရမ်း",
  "Kyauktada": "ကျောက်တံတား",
  "Kyauktan": "ကျောက်တန်း",
  "Kyimyindaing": "ကြည့်မြင်တိုင်",
  "Kungyangon": "ကွမ်းခြံကုန်း",
  "Lanmadaw": "လမ်းမတော်",
  "Latha": "လသာ",
  "Mayangon": "မရမ်းကုန်း",
  "Mingala Taungnyunt": "မင်္ဂလာတောင်ညွန့်",
  "Mingaladon": "မင်္ဂလာဒုံ",
  "North Dagon": "မြောက်ဒဂုံ",
  "North Okkalapa": "မြောက်ဥက္ကလာပ",
  "Pabedan": "ပန်းဘဲတန်း",
  "Pazundaung": "ပုဇွန်တောင်",
  "Sanchaung": "စမ်းချောင်း",
  "Seikgyi Kanaungto": "ဆိပ်ကြီး/ခနောင်တို",
  "Shwepyithar": "ရွှေပြည်သာ",
  "South Dagon": "ဒဂုံမြို့သစ်(တောင်ပိုင်း)",
  "South Okkalapa": "တောင်ဥက္ကလာပ",
  "Tamwe": "တာမွေ",
  "Taikkyi": "တိုက်ကြီး",
  "Thaketa": "သာကေတ",
  "Thingangyun": "သင်္ဃန်းကျွန်း",
  "Thongwa": "သုံးခွ",
  "Twantay": "တွံတေး",
  "Yankin": "ရန်ကင်း",
  "Amarapura": "အမရပူရ",
  "Chanayethazan": "ချမ်းအေးသာဇံ",
  "Chanmyathazi": "ချမ်းမြသာစည်",
  "Kyaukse": "ကျောက်ဆည်",
  "Kyaukpadaung": "ကျောက်ပန်းတောင်း",
  "Madaya": "မတ္တရာ",
  "Mahaaungmyay": "မဟာအောင်မြေ",
  "Mahlaing": "မလှိုင်",
  "Meiktila": "မိတ္ထီလာ",
  "Mogok": "မိုးကုတ်",
  "Myingyan": "မြင်းခြံ",
  "Myittha": "မြစ်သား",
  "Nyaung-U": "ညောင်ဦး",
  "Patheingyi": "ပုသိမ်ကြီး",
  "Pyigyitagun": "ပြည်ကြီးတံခွန်",
  "Pyin Oo Lwin": "ပြင်ဦးလွင်",
  "Pyinmana": "ပျဉ်းမနား",
  "Singu": "စဉ့်ကူး",
  "Tada-U": "တံတားဦး",
  "Taungtha": "တောင်သာ",
  "Thabeikkyin": "သပိတ်ကျင်း",
  "Wundwin": "ဝမ်းတွင်း",
  "Yamethin": "ရမည်းသင်း",
  "Ye-U": "ရေဦး",
  "Dekkhinathiri": "ဒက္ခိဏသီရိ",
  "Lewe": "လယ်ဝေး",
  "Ottarathiri": "ဥတ္တရသီရိ",
  "Poke Ba Thi Ri": "ပုဗ္ဗသီရိ",
  "Tatkon": "တပ်ကုန်း",
  "Zabuthiri": "ဇမ္ဗူသီရိ",
  "Zeyarthiri": "ဇေယျာသီရိ",
  "Bogale": "ဘိုကလေး",
  "Danubyu": "ဓနုဖြူ",
  "Hinthada": "ဟင်္သာတ",
  "Kyaiklat": "ကျိုက်လတ်",
  "Labutta": "လပွတ္တာ",
  "Maubin": "မအူပင်",
  "Myanaung": "မြန်အောင်",
  "Myaungmya": "မြောင်းမြ",
  "Ngapudaw": "ငပုတော",
  "Pathein": "ပုသိမ်",
  "Pyapon": "ဖျာပုံ",
  "Wakema": "ဝါးခယ်မ",
  "Yegyi": "ရေကြည်",
  "Zalun": "ဇလွန်",
  "Bago": "ပဲခူး",
  "Daik-U": "ဒိုက်ဦး",
  "Kawa": "ကဝ",
  "Kyaukkyi": "ကျောက်ကြီး",
  "Kyauktaga": "ကျောက်တံခါး",
  "Nyaunglebin": "ညောင်လေးပင်",
  "Okpho": "အုတ်ဖို",
  "Padaung": "ပန်းတောင်း",
  "Paungde": "ပေါင်းတည်",
  "Phyu": "ဖြူး",
  "Pyay": "ပြည်",
  "Shwegyin": "ရွှေကျင်",
  "Taungoo": "တောင်ငူ",
  "Thanatpin": "သနပ်ပင်",
  "Tharyarwady": "သာယာဝတီ",
  "Waw": "ဝေါ",
  "Zigon": "ဇီးကုန်း",
  "Falam": "ဖလမ်း",
  "Hakha": "ဟားခါး",
  "Kanpetlet": "ကန်ပက်လက်",
  "Matupi": "မတူပီ",
  "Mindat": "မင်းတပ်",
  "Paletwa": "ပလက်ဝ",
  "Tedim": "တီးတိန်",
  "Thantlang": "ထန်တလန်",
  "Tonzang": "တွန်းဇန်",
  "Bhamo": "ဗန်းမော်",
  "Chipwi": "ချီဖွေ",
  "Hpakant": "ဖားကန့်",
  "Injangyang": "အင်ဂျန်းယန်",
  "Machanbaw": "မချမ်းဘော",
  "Mansi": "မံစီ",
  "Mohnyin": "မိုးညှင်း",
  "Momauk": "မိုးမောက်",
  "Myitkyina": "မြစ်ကြီးနား",
  "Putao": "ပူတာအို",
  "Shwegu": "ရွှေကူ",
  "Sumprabum": "ဆွမ်ပရာဘွမ်",
  "Tanai": "တနိုင်း",
  "Waingmaw": "ဝိုင်းမော်",
  "Bawlakhe": "ဘောလခဲ",
  "Demoso": "ဒီမောဆို",
  "Hpasawng": "ဖားဆောင်း",
  "Hpruso": "ဖျဆို",
  "Loikaw": "လွိုင်ကော်",
  "Mese": "မယ်စဲ",
  "Shadaw": "ရှားတော",
  "Hlaingbwe": "လှိုင်းဘွဲ့",
  "Hpa-An": "ဘားအံ",
  "Kawkareik": "ကော့ကရိတ်",
  "Kyainseikgyi": "ကြာအင်းဆိပ်ကြီး",
  "Myawaddy": "မြဝတီ",
  "Thandaunggyi": "သံတောင်ကြီး",
  "Chauk": "ချောက်",
  "Gangaw": "ဂန့်ဂေါ",
  "Magway": "မကွေး",
  "Minbu": "မင်းဘူး",
  "Myothit": "မြို့သစ်",
  "Natmauk": "နတ်မောက်",
  "Ngape": "ငဖဲ",
  "Pakokku": "ပခုက္ကူ",
  "Pauk": "ပေါက်",
  "Pwintbyu": "ပွင့်ဖြူ",
  "Salin": "စလင်း",
  "Seikphyu": "ဆိပ်ဖြူ",
  "Sidoktaya": "စေတုတ္တရာ",
  "Taungdwingyi": "တောင်တွင်းကြီး",
  "Thayet": "သရက်",
  "Yenangyaung": "ရေနံချောင်း",
  "Bilin": "ဘီးလင်း",
  "Chaungzon": "ချောင်းဆုံ",
  "Kyaikto": "ကျိုက်ထို",
  "Kyaikmaraw": "ကျိုက်မရော",
  "Mawlamyine": "မော်လမြိုင်",
  "Mudon": "မုဒုံ",
  "Paung": "ပေါင်",
  "Thaton": "သထုံ",
  "Ye": "ရေး",
  "Ann": "အမ်း",
  "Buthidaung": "ဘူးသီးတောင်",
  "Gwa": "ဂွ",
  "Kyaukpyu": "ကျောက်ဖြူ",
  "Kyauktaw": "ကျောက်တော်",
  "Maungdaw": "မောင်တော",
  "Minbya": "မင်းပြား",
  "Mrauk-U": "မြောက်ဦး",
  "Myebon": "မြေပုံ",
  "Pauktaw": "ပေါက်တော",
  "Ponnagyun": "ပုဏ္ဏားကျွန်း",
  "Ramree": "ရမ်းဗြဲ",
  "Rathedaung": "ရသေ့တောင်",
  "Sittwe": "စစ်တွေ",
  "Taungup": "တောင်ကုတ်",
  "Thandwe": "သံတွဲ",
  "Ayadaw": "အရာတော်",
  "Banmauk": "ဗန်းမောက်",
  "Budalin": "ဘုတလင်",
  "Chaung-U": "ချောင်းဦး",
  "Hkamti": "ခန္တီး",
  "Homalin": "ဟုမ္မလင်း",
  "Indaw": "အင်းတော်",
  "Kale": "ကလေး",
  "Katha": "ကသာ",
  "Kawlin": "ကောလင်း",
  "Khin-U": "ခင်ဦး",
  "Mawlaik": "မော်လိုက်",
  "Mingin": "မင်းကင်း",
  "Monywa": "မုံရွာ",
  "Myaung": "မြောင်",
  "Myinmu": "မြင်းမူ",
  "Pinlebu": "ပင်လည်ဘူး",
  "Sagaing": "စစ်ကိုင်း",
  "Shwebo": "ရွှေဘို",
  "Tabayin": "ဒီပဲယင်း",
  "Tamu": "တမူး",
  "Taze": "တန့်ဆည်",
  "Wetlet": "ဝက်လက်",
  "Yinmabin": "ယင်းမာပင်",
  "Hopang": "ဟိုပန်",
  "Hseni": "သိန္နီ",
  "Kalaw": "ကာလော",
  "Kengtung": "ကျိုင်းတုံ",
  "Kunhing": "ကွန်ဟိန်း",
  "Kyaukme": "ကျောက်မဲ",
  "Lashio": "လားရှိုး",
  "Lawksawk": "လောက်ဆော",
  "Loilen": "လွိုင်လင်",
  "Mong Hsat": "မိုင်းဆတ်",
  "Mong Kung": "မိုင်းကอง",
  "Mong Pan": "မိုင်းပန်",
  "Mong Ping": "မိုင်းပင်း",
  "Mong Ton": "မိုင်းတုံ",
  "Mong Yai": "မိုင်းရယ်",
  "Mong Yang": "မိုင်းယန်း",
  "Muse": "မူဆယ်",
  "Namhsan": "နမ့်ဆန်",
  "Namtu": "နမ္မတူ",
  "Nawnghkio": "နောင်ချို",
  "Pindaya": "ပင်းတယ",
  "Pinlaung": "ပင်လောင်း",
  "Tachileik": "တာချီလိတ်",
  "Taunggyi": "တောင်ကြီး",
  "Ywangan": "ရွာငံ",
  "Bokpyin": "ဘုတ်ပြင်း",
  "Dawei": "ထားဝယ်",
  "Kawthoung": "ကော့သောင်း",
  "Kyunsu": "ကျွန်းစု",
  "Launglon": "လောင်းလုံး",
  "Myeik": "မြိတ်",
  "Palaw": "ပုလော",
  "Tanintharyi": "တနင်္သာရီ",
  "Thayetchaung": "သရက်ချောင်း",
  "Yebyu": "ရေဖြူ",
} as const;

